services:
  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"

  api1:
    image: ghcr.io/joojf/rinha-2026-python-api:latest
    platform: linux/amd64
    pull_policy: always
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165MB"

  api2:
    image: ghcr.io/joojf/rinha-2026-python-api:latest
    platform: linux/amd64
    pull_policy: always
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165MB"

networks:
  default:
    driver: bridge
