volumes:
  sockets:

services:
  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "20MB"

  api1:
    build:
      context: ./api
      platforms:
        - linux/amd64
    environment:
      LISTEN_UDS: /sockets/api1.sock
    volumes:
      - sockets:/sockets
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "165MB"

  api2:
    build:
      context: ./api
      platforms:
        - linux/amd64
    environment:
      LISTEN_UDS: /sockets/api2.sock
    volumes:
      - sockets:/sockets
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "165MB"

networks:
  default:
    driver: bridge
