worker_processes 1;
worker_rlimit_nofile 4096;

events {
    worker_connections 2048;
    multi_accept on;
    use epoll;
}

http {
    access_log off;
    sendfile on;
    tcp_nodelay on;
    tcp_nopush off;
    keepalive_requests 100000;
    keepalive_timeout 75s;

    upstream api_backends {
        server unix:/sockets/api1.sock;
        server unix:/sockets/api2.sock;
        keepalive 64;
        keepalive_requests 100000;
    }

    server {
        listen 9999 default_server backlog=2048;

        location / {
            proxy_pass http://api_backends;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_next_upstream error timeout http_502 http_503;
        }
    }
}
